FROM node:22-slim

WORKDIR /app
ENV NODE_ENV=development

COPY package*.json ./
RUN npm ci

COPY src ./src
COPY public ./public
COPY index.html ./
COPY vite.config.ts ./
COPY tsconfig.json ./
COPY tsconfig.app.json ./
COPY tsconfig.node.json ./

EXPOSE 5173

CMD ["npx", "vite", "--host"]
